### ISSUE TITLE
option to only regenerate old certificates

### ISSUE THREAD

**Issue by drzraf** [felixfontein/letsencrypt-ansible#5]
That would be a neat option, (eg: key expiring in less that <a custom threshold>)

**Comment by felixfontein** [comment]
It would be neat, but I don't think it's really necessary. The nice thing about Let's Encrypt is that you don't have to care about maximizing a certificate's lifetime (since it doesn't cost you any money to just get a new one). I renew my certs roughly every two months, and if I need a cert inbetween for a new (sub-)domain, I just get one and renew it together with the other ones, even though the new certificate is (much) less than two months old at that point.

Anyway, if you want to implement this without adding a lot of new complexity, feel free to do so!

**Comment by wkoszek** [comment]
Do you agree @drzraf there's nothing more here to be done and we could close it?

**Comment by drzraf** [comment]
I don't completely agree.
I keep having email notification for old certificate even if I renewed them. Thus renewing needlessly imply needless "expiration notification".
Unrelated, but adding to this that even certbot makes very hard, if not impossible, to change email address when certificates are generated without certbot, https://github.com/certbot/certbot/issues/3839

**Comment by felixfontein** [comment]
Well, feel free to add support for this to the ansible role. :)

For a hackish implementation, you can dump the certificate with `openssl x509 -inform pem -text -in {{ filename }}`, grep for `Not After`, and extract the date (cut off everything until `:`). If you stored the result of grep in `expiry_date`, you can check whether it expires with:
``
- name: Check for expiry
  local_action: command python -c "from datetime import datetime, timedelta; datetime.strptime('{{ expiry_date[expiry_date.index(':')+1:].strip() }}', '%b %d %H:%M:%S %Y %Z' > datetime.now() + timedelta(weeks=1))"
  register: expiring_soon
  run_once: true
``
the variable `expiring_soon` should now contain `"True"` if the certificate expires in the next seven days, or `"False"` if not.

**Comment by felixfontein** [comment]
If you found a good solution for this, feel free to open a PR. Until then, I'm closing this.
