### ISSUE TITLE
use a more common acme implementation

### ISSUE THREAD

**Issue by drzraf** [felixfontein/letsencrypt-ansible#7]
The current acme_tiny implementation (acme_lib.py) comes from a custom branch of an unmaintained fork.
For a long-term support perspective it'd be safer to choose a well-supported implementation since it's a hard-dependency for the whole role.

**Comment by felixfontein** [comment]
Do you have any suggestions for another ACME client which provides what the role needs?

**Comment by drzraf** [comment]
Why not going back to the original library from https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py for example?

**Comment by felixfontein** [comment]
Because it cannot be used in two phases. That was the whole point of forking acme_tiny. It needs to run on the server, so the account private key needs to be on the server as well. Or you need to setup sshfs or something similar to have the challenge files show up on your server. (But what if you need the files to appear on more than one server, for example because of load balancing?) Or add some other magic.

So, no, it doesn't satisfy the requirements to be useable in this role.

**Comment by wkoszek** [comment]
I'm looking at this repo and I think we could close this issue @felixfontein  ?

**Comment by drzraf** [comment]
As you want, but IMHO this is the main issue for the project and what makes it the most "fragile".

**Comment by felixfontein** [comment]
I don't mind to keep this open, but I'm not sure whether we'll find a useable replacement.
